Repository hexedtech/codemp, pull requests merged in 2024-10, with the labels that each got.

#36 chore: cargo fmt
  build.rs
  src/api/controller.rs
  src/api/mod.rs
  src/buffer/worker.rs
  src/cursor/worker.rs
  src/errors.rs
  src/ext.rs
  src/ffi/java/buffer.rs
  src/ffi/java/client.rs
  src/ffi/java/cursor.rs
  src/ffi/java/ext.rs
  src/ffi/java/mod.rs
  src/ffi/java/workspace.rs
  src/ffi/js/buffer.rs
  src/ffi/js/client.rs
  src/ffi/js/cursor.rs
  src/ffi/js/ext.rs
  src/ffi/js/mod.rs
  src/ffi/js/workspace.rs
  src/ffi/lua/buffer.rs
  src/ffi/lua/client.rs
  src/ffi/lua/cursor.rs
  src/ffi/lua/ext/a_sync.rs
  src/ffi/lua/ext/callback.rs
  src/ffi/lua/ext/log.rs
  src/ffi/lua/ext/mod.rs
  src/ffi/lua/mod.rs
  src/ffi/lua/workspace.rs
  src/lib.rs
  src/network.rs
  src/prelude.rs
  src/workspace.rs
Labels: tweak

#31 feat(lua): cancel promise
  dist/lua/annotations.lua
  src/ffi/lua/ext/a_sync.rs
Labels: lua, improvement

#32 fix: leave_workspace returns like detach
  src/client.rs
  src/workspace.rs
Labels: bug, core

#33 feat: workspace receiver
  dist/java/src/mp/code/Workspace.java
  dist/java/src/mp/code/data/DetachResult.java
  dist/lua/annotations.lua
  dist/py/src/codemp/codemp.pyi
  src/api/controller.rs
  src/buffer/controller.rs
  src/buffer/worker.rs
  src/cursor/controller.rs
  src/ext.rs
  src/ffi/java/buffer.rs
  src/ffi/java/cursor.rs
  src/ffi/java/workspace.rs
  src/ffi/js/buffer.rs
  src/ffi/js/cursor.rs
  src/ffi/js/workspace.rs
  src/ffi/lua/ext/a_sync.rs
  src/ffi/lua/ext/callback.rs
  src/ffi/lua/workspace.rs
  src/ffi/python/controllers.rs
  src/ffi/python/workspace.rs
  src/lib.rs
  src/prelude.rs
  src/workspace.rs
Labels: feature, core

#39 Feat: Buffer ack-ing
  Cargo.lock
  Cargo.toml
  dist/java/src/mp/code/BufferController.java
  dist/java/src/mp/code/CursorController.java
  dist/java/src/mp/code/data/BufferUpdate.java
  dist/java/src/mp/code/data/Cursor.java
  dist/java/src/mp/code/data/Selection.java
  dist/java/src/mp/code/data/TextChange.java
  dist/lua/annotations.lua
  dist/py/src/codemp/codemp.pyi
  src/api/change.rs
  src/api/config.rs
  src/api/controller.rs
  src/api/cursor.rs
  src/api/mod.rs
  src/buffer/controller.rs
  src/buffer/worker.rs
  src/cursor/controller.rs
  src/cursor/worker.rs
  src/ffi/java/buffer.rs
  src/ffi/java/cursor.rs
  src/ffi/java/mod.rs
  src/ffi/java/workspace.rs
  src/ffi/js/buffer.rs
  src/ffi/js/cursor.rs
  src/ffi/js/workspace.rs
  src/ffi/lua/buffer.rs
  src/ffi/lua/cursor.rs
  src/ffi/lua/ext/a_sync.rs
  src/ffi/lua/ext/callback.rs
  src/ffi/lua/ext/mod.rs
  src/ffi/lua/workspace.rs
  src/ffi/mod.rs
  src/ffi/python/controllers.rs
  src/lib.rs
  src/prelude.rs
Labels: feature, core

#42 fix: typos in clear_callback
  src/ffi/lua/workspace.rs
  src/ffi/python/workspace.rs
Labels: bug

#38 fix: warn when clipping, gen agent id once
  src/buffer/worker.rs
Labels: tweak

#44 fix: make version return a static string
  src/ffi/java/ext.rs
  src/ffi/js/ext.rs
  src/ffi/lua/mod.rs
  src/ffi/python/mod.rs
  src/lib.rs
Labels: tweak

#45 feat: optimize release build for smaller size
  Cargo.toml
Labels: core, improvement

#47 docs(ffi): comparison examples
  src/ext.rs
  src/ffi/mod.rs
  src/lib.rs
Labels: documentation

#51 feat/config-default
  src/api/config.rs
  src/ffi/mod.rs
Labels: core, improvement

#52 docs: improved a bit initial wording in readme
  README.md
Labels: documentation

#53 fix: panic and docs
  Cargo.toml
  dist/py/src/codemp/codemp.pyi
  src/ffi/mod.rs
Labels: bug, documentation, lua, python

#55 fix(java): bad user_list signature
  dist/java/src/mp/code/Workspace.java
Labels: bug, java

#59 fix(lua): annotations for workspace event
  dist/lua/annotations.lua
Labels: lua, tweak

#62 chore: lua annotations, cargo fmt
  dist/lua/annotations.lua
  src/ffi/js/buffer.rs
  src/ffi/js/workspace.rs
Labels: lua, javascript, tweak

#61 fix: properly update branch version
  src/buffer/controller.rs
  src/buffer/worker.rs
Labels: bug, needs research, core
